#ifndef TELEOP2SERVO__GAMEPAD_CONFIG_HPP_
#define TELEOP2SERVO__GAMEPAD_CONFIG_HPP_

enum AXIS
{
    LEFT_STICK_X = 0,
    LEFT_STICK_Y = 1,
    RIGHT_MOUSE_X = 2,
    RIGHT_MOUSE_Y = 3,
    LEFT_MOUSE_X = 4,
    LEFT_MOUSE_Y = 5,
    LEFT_TRIGGER = 6,
    RIGHT_TRIGGER = 7
};

enum BUTTONS
{
    LEFT_MOUSE_TOUCH = 0,
    RIGHT_MOUSE_TOUCH= 1,
    A_BUTTON = 2,
    B_BUTTON = 3,
    X_BUTTON = 4,
    Y_BUTTON = 5,
    LEFT_BUMPER = 6,
    ROGHT_BUMPER = 7,
    LEFT_TRIGGER_BUTTON = 8,
    RIGHT_TRIGGER_BUTTON = 9,
    LEFT_ARROW = 10,
    RIGHT_ARROW = 11,
    POWER_ON_OFF = 12,
    LEFT_STICK_BUTTON = 13,
    RIGHT_MOUSE_BUTTON = 14,
    LEFT_BACK_BUTTON = 15,
    RIGHT_BACK_BUTTON = 16,
    LEFT_MOUSE_TOP_BUTTON = 17,
    LEFT_MOUSE_DOWN_BUTTON = 18,
    LEFT_MOUSE_LEFT_BUTTON = 19,
    LEFT_MOUSE_RIGHT_BUTTON = 20
};

#endif  // TELEOP2SERVO__GAMEPAD_CONFIG_HPP_
