gamepad_teleop_node:
  ros__parameters:
    teleop:
      servo_publish_hz: 250.0
      servo_ticks_per_policy_step: 10

    # joy topic
    joy_topic: "/joy"

    # servo topics
    twist_topic: "/servo_node/delta_twist_cmds"
    joint_topic: "/servo_node/delta_joint_cmds"
    queue_size: 10

    base_frame_id: "base_link"
    ee_frame_id: "tool0"

    joint_names:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    # speeds
    joint_vel_step: 0.5     # [rad/s]
    joint_vel_cont_max: 0.3   # [rad/s]

    twist_lin_step: 0.01      # [m/s]
    twist_lin_cont_max: 0.1   # [m/s]

    twist_ang_step: 0.05      # [rad/s]
    twist_ang_cont_max: 0.25  # [rad/s]
