teleop2servo:
  ros__parameters:
    publish_hz: 250

    step_publish_ticks: 25

    # serwo topics
    twist_topic: "/servo_node/delta_twist_cmds"
    joint_topic: "/servo_node/delta_joint_cmds"
    queue_size: 10

    base_frame_id: "base_link"
    ee_frame_id: "tool0"

    joint_names:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    # speeds
    joint_vel_step: 0.3
    joint_vel_cont_max: 1.0

    twist_lin_step: 0.3
    twist_lin_cont_max: 1.0

    twist_rot_step: 0.3
    twist_rot_cont_max: 1.0
