teleop_keyboard:
  ros__parameters:
    joint_cmd_topic: /servo_node/delta_joint_cmds
    publish_hz: 100
    cmd_timeout_ms: 200

    joint_names:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    joint_velocity: 0.4   # rad/s
    deadman_enabled: true

    keymap:
      joint0_plus: "1"
      joint0_minus: "q"
      joint1_plus: "2"
      joint1_minus: "w"
      joint2_plus: "3"
      joint2_minus: "e"
      joint3_plus: "4"
      joint3_minus: "r"
      joint4_plus: "5"
      joint4_minus: "t"
      joint5_plus: "6"
      joint5_minus: "y"